# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "oss_vendor_synaptics"
BBFILE_PATTERN_oss_vendor_synaptics = "^${LAYERDIR}/"
BBFILE_PRIORITY_oss_vendor_synaptics = "6"

LAYERDEPENDS_oss_vendor_synaptics = "core"
LAYERSERIES_COMPAT_oss_vendor_synaptics = "kirkstone"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBMASK += "${RDKROOT}/rdke/vendor/soc/meta-synaptics/recipes-core/systemd/systemd_%.bbappend"
